<!DOCTYPE html>
<html>
<head>
	<title>learning js</title>
	<script type="text/javascript" src="E:\important\asd.js"></script>
	<style type="text/css">
			p {
				color: rgb(300, 300, 0);
			}
			body {
				background-color: rgb(300, 0, 0);
			}
			 {
				color: rgb(200, 0, 400,);
			}
			table, thead, tr, td {
				border: 1px solid black
			}
	</style>
</head>
<body>
	<a href="#img">img</a>
	<P>
		HELLO. I AM ARIHANT JAIN. I AM LEARNING JAVASCRIPT.
	</P>
	<table>
		<thead>
			<tr>
				<td>
					myname
				</td>
				<td>
					age
				</td>
			</tr>
		</thead>
		<tr>
			<td>
				arihant jain
			</td>
			<td>
				15 years
			</td>
		</tr>
	</table>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
	<img src="https://www.kasandbox.org/programming-images/avatars/aqualine-seed.png" width="400" height="400" id="img">
	
		
	
</body>
</html>
